version: "2"
services:
  web:
    image: registry.cn-wulanchabu.aliyuncs.com/meijinerp/qrcode_server
    command: npm start
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "8080:8080"
